---
title: "test"
author: "Joel H. Reynolds"
date: "5/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
})
```


```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1", method = "libcurl"), 
                stringsAsFactors = FALSE)
```

```{r}
#Calculate median escapement
median_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, SASAP.Region, Year, Location) %>%   #for each Species, Region, Year, Location
  summarize(escapement = sum(DailyCount)) %>%           # calculate the annual total escapement
  group_by(Species) %>%                                 # now sum across regions, locations, and years
  summarize(median_escapement = median(escapement))

ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```


```{r echo=FALSE}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

datatable(locations)

#Easy way to add R data on top of maps
if (0) {leaflet(locations) %>% 
  addTiles() %>%    #background of the map, from OpenStreet
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location)
# but temporary issue w/ certificates from leaflet
}

# Use a custom marker so Leaflet doesn't try to grab the marker images from 
# its CDN (this was brought up in 
# https://github.com/NCEAS/sasap-training/issues/22)
markerIcon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-icon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41,
  shadowUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-shadow.png",
  shadowWidth = 41, shadowHeight = 41,
  shadowAnchorX = 13, shadowAnchorY = 41)

if (0) {leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon = markerIcon)
}

# Fix erroneous longitudes
locs <- locations %>% mutate(Longitude = abs(Longitude) * -1)

leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon = markerIcon)
```

